### PR TITLE
Fix TypeScript linting issues around Registry and Schema

### LINKED ISSUE #382: TypeScript 3.9 linting issues
```
Error: /home/travis/build/miragejs/miragejs/types/index.d.ts:214:20
ERROR: 214:20  expect  TypeScript@3.9 compile error: 
Type 'Registry' does not satisfy the constraint 'Record<string, { id?: string | undefined; attrs: Record<string, unknown>; modelName: string; save(): void; update<K extends never>(key: K, value: {}[K]): void; update(changes: Partial<{}>): void; destroy(): void; reload(): void; }>'.
/home/travis/build/miragejs/miragejs/types/tests/db-test.ts:34:1
ERROR: 34:1    expect  TypeScript@3.9 expected type to be:
  any
got:
  void
ERROR: 35:1    expect  TypeScript@3.9 expected type to be:
  any
got:
  void
ERROR: 36:1    expect  TypeScript@3.9 expected type to be:
  any
got:
  void
/home/travis/build/miragejs/miragejs/types/tests/schema-test.ts:3:30
ERROR: 3:30    expect  TypeScript@3.9 compile error: 
Type '{ foo: { attr: string; }; bar: { prop: number; }; }' does not satisfy the constraint 'Record<string, { id?: string | undefined; attrs: Record<string, unknown>; modelName: string; save(): void; update<K extends never>(key: K, value: {}[K]): void; update(changes: Partial<{}>): void; destroy(): void; reload(): void; }>'.
  Property 'foo' is incompatible with index signature.
    Type '{ attr: string; }' is missing the following properties from type '{ id?: string | undefined; attrs: Record<string, unknown>; modelName: string; save(): void; update<K extends never>(key: K, value: {}[K]): void; update(changes: Partial<{}>): void; destroy(): void; reload(): void; }': attrs, modelName, save, update, and 2 more.
```

### PR DESCRIPTION
**Pull request by zoltan-nz**
fix #382

### CODE REVIEW

**Comment by zoltan-nz** [comment]
@chriskrycho @samselikoff 

Hey guys, after the Schema type update linter is started to complain.

Please find here:
- Upgrade dtslint, tslint and typescript packages
- Update db-test
- Fix RouteHandler
- Update schema-test
- Reformat the code with the latest Prettier settings

Could you please review this PR? Thanks. :)

**Comment by zoltan-nz** [comment]
Tests are green: https://travis-ci.org/github/zoltan-nz/miragejs/jobs/669617819

**Comment by samselikoff** [comment]
Not really qualified to review this yet but I am going to start working on that so I can help with maintenance.

@chriskrycho mind jumping in? And @zoltan-nz after this do you think we can cut a release?

Also, so I can start learning could you explain a bit about what changed with the linter/new version of TS that led to this issue?

File: types/index.d.ts [hunk 1]
```diff
@@ -210,8 +210,8 @@ declare module "miragejs/server" {
   type MaybePromise<T> = T | PromiseLike<T>;
 
   /** A callback that will be invoked when a given Mirage route is hit. */
-  export type RouteHandler<Registry> = (
-    schema: Schema<Registry>,
+  export type RouteHandler<T extends Registry<any, any>> = (
```
Comment (jamescdavis) [inline types/index.d.ts:213]: I don't think this is what we want to do. Instead, I think Registry should be given defaults:
```ts
declare module "miragejs/-types" {
  ⋮
  export type Registry<
    Models extends Record<string, ModelDefinition> = Record<string, ModelDefinition>,
    Factories extends Record<string, FactoryDefinition> = Record<string, FactoryDefinition>
  > = {
    [K in keyof Models | keyof Factories]: ModelInstance<
      ExtractModelData<Models, K> & ExtractFactoryData<Factories, K>
    >;
  };
  ⋮
```
and then just have
```suggestion
  export type RouteHandler<T extends Registry> = (
```

File: types/index.d.ts [hunk 2]
```diff
@@ -438,7 +438,12 @@ declare module "miragejs/orm/schema" {
   /**
    * An interface to the Mirage ORM that allows for querying and creating records.
    */
-  export default class Schema<Registry extends Record<string, ModelInstance> = Record<string, ModelInstance>> {
+  export default class Schema<
+    Registry extends Record<string, ModelInstance> = Record<
+      string,
+      ModelInstance
+    >
```
Comment (jamescdavis) [inline types/index.d.ts:445]: Instead of defining `Registry` here, we should be able to 
```ts
import { Registry } from "miragejs";
```
and here
```ts
  export default class Schema<R extends Registry> {
    ⋮
    create<
      K extends keyof R,
      Init extends R[K],
      Data extends Partial<ModelInitializer<Init>>
    >(
      modelName: K,
      data?: Data
    ): Init & { [K in keyof Init & keyof Data]: Exclude<Init[K], undefined> };
    ⋮
```
I guess this could be a later refinement, though? v0v

File: types/index.d.ts (hunk 1 above)
Comment (zoltan-nz) [reply types/index.d.ts]: @jamescdavis Fantastic suggestion. Thank you. It really makes sense and clean up the the usage of Registry type. Love it. Please review the update. What do you think? :)

File: types/index.d.ts (hunk 2 above)
Comment (zoltan-nz) [reply types/index.d.ts]: I updated the whole Schema definition based on your suggestion. Really appreciate. :)

File: types/tests/schema-test.ts [hunk 3]
```diff
@@ -21,7 +21,7 @@ schema.create("foo", { x: true }); // $ExpectError
 schema.create("cow"); // $ExpectError
 
 schema.find("foo", "123"); // $ExpectType ModelInstance<FlattenRelationships<Assign<{}, { attr: string; }>> & FlattenFactoryMethods<Assign<{}, { attr: string; }>>> | null
-schema.find("foo", ["123"]).models[0]; // $ExpectType ModelInstance<FlattenRelationships<Assign<{}, { attr: string; }>> & FlattenFactoryMethods<Assign<{}, { attr: string; }>>>
+schema.find("foo", ["123"]).models[0]; // $ExpectType ["foo"]
```
Comment (zoltan-nz) [inline types/tests/schema-test.ts:24]: @jamescdavis is this expected type right?

**Comment by zoltan-nz** [comment]
> Not really qualified to review this yet but I am going to start working on that so I can help with maintenance.
> 
> @chriskrycho mind jumping in? And @zoltan-nz after this do you think we can cut a release?
> 
> Also, so I can start learning could you explain a bit about what changed with the linter/new version of TS that led to this issue?

Hi Sam, I suppose, the last changes in the previous PR when we upgraded the type of Registry changed the behaviour of the Registry type. For some reason Travis was not running on that PR anymore... and I don't see it is running on this PR either. (I added it manually, but should be part of this PR, I guess. https://travis-ci.org/github/zoltan-nz/miragejs)

Anyway, so the linter was right to raise errors in other places, because of the Registry change, we had to update types on other places as well. @jamescdavis suggestion was super helpful.

It looks `dtslint` is always test types with the proposed version of TypeScript, so linting issues are not really related to version `3.9`, they were real issues. (I update the title of this PR.)

@samselikoff could you please help with the Travis setup, it would be great if it would block the PR if there is any issue.

**Comment by samselikoff** [comment]
Gotcha. Thanks for explaining.

Yep, I noticed travis seemed off so I'll investigate 👍

**Comment by samselikoff** [comment]
It does look like this PR ran 🤔 

https://travis-ci.org/github/miragejs/miragejs/builds/669898537

Not sure why it's not showing up in UI. Might be a gh/ =travis webhook issue

**Comment by samselikoff** [comment]
think its working again 👍  This guy good to go?

File: types/index.d.ts [hunk 4]
```diff
@@ -448,46 +454,37 @@ declare module "miragejs/orm/schema" {
...
     ): Init & { [K in keyof Init & keyof Data]: Exclude<Init[K], undefined> };
 
     /** Locates one or more existing models of the given type by ID(s). */
-    find<K extends keyof Registry>(type: K, id: string): Registry[K] | null;
-    find<K extends keyof Registry>(
-      type: K,
-      ids: string[]
-    ): Collection<Registry[K]>;
+    find<K extends keyof R>(type: K, id: string): R[K] | null;
+    find<K extends keyof R>(type: K, ids: string[]): Collection<[K]>;
```
Comment (jamescdavis) [inline types/index.d.ts:467]: This should be:
```suggestion
    find<K extends keyof R>(type: K, ids: string[]): Collection<R[K]>;
```
then
```ts
schema.find("foo", ["123"]).models[0];
```
in `types/tests/schema-test.ts` will return the correct type again.

File: types/tests/schema-test.ts (hunk 3 above)
Comment (jamescdavis) [reply types/tests/schema-test.ts:24]: Nope! See my review below.

File: types/index.d.ts (hunk 4 above)
Comment (zoltan-nz) [reply types/index.d.ts]: Thanks for the suggestion. Just updated. What do you think?

**Comment by zoltan-nz** [comment]
@samselikoff @jamescdavis Hope the build gonna be green and I think it is ready to go. What do you think @jamescdavis?

**Comment by samselikoff** [comment]
build is green

**Comment by samselikoff** [comment]
Status?

**Comment by samselikoff** [comment]
(Sorry to bother but since master is failing it's affecting other work)

**Comment by zoltan-nz** [comment]
@jamescdavis request was implemented, so it is ready to merge.

**Comment by jamescdavis** [comment]
Sorry, yeah, glad this was merged. @zoltan-nz, I tried to contact you on Discord. I wanted to discuss the registry.
